FROM tensorflow/tensorflow:latest-gpu   

WORKDIR /usr/src/app


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install tensorflow-gpu 
RUN nvidia-smi

USER 1000:1000

COPY . .
