version: '3.6'  
services: 
  download:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: python financial_api.py 
  convert:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: python convert_csv.py
  trainer:
    build:
      dockerfile: Dockerfile-gpu
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: python main.py
  predict:
    build:
      dockerfile: Dockerfile-gpu
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: cd ./ai && python predict.py
  bot:
    build:
      dockerfile: Dockerfile-gpu
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: python bot.py
